[actions]
"actions-rust-lang/rustfmt" = "^1"
"actions-rust-lang/setup-rust-toolchain" = "~1.15.2"
"actions/checkout" = "^6"
"actions/create-github-app-token" = "^2"
"actions/download-artifact" = "^7"
"actions/upload-artifact" = "^6"
"jdx/mise-action" = "^3"
"release-plz/action" = "^0.5"
"rust-lang/crates-io-auth-action" = "~1.0.3"
